/*********************************************/
/*
 * @file 	cyRandom
 * @author	Marco "Swampertor" Millan
 * @date	3/09/2021
 * @brief	a Random number generator that uses several systems:
 *        as base, it uses xOrShift for fast pseudorandom numbers
 *        it can also use ziggurath to generate numbers 
 *        ALSO it can create CPRNG if you want to do
 *        something cryptographically safe.
 *        The init generates a pseudorandom number using 
 *        the mersenne twist approach
 *
 */
/******************************************** */
#pragma once

#include <chrono>


#include "cyRandomPrerequisites.h"
#include "cyZiggurat.h"
#include "cyMT.h"

#include <cyVector2f.h>
#include <cyVector2i.h>
#include <cyVector3f.h>
#include <cyVector4f.h>
#include <cyColor.h>

namespace CYLLENE_SDK {

  namespace RANDOM_METHOD
  {
  BETTER_ENUM(E, uint32,
              eZIGGURAT,
              eMT,
              eBBS,
              eMSM);
  }



struct CY_RANDOM_EXPORT Random
{
public:

  static void 
  init() {
    m_method = 0;
    std::mt19937 random(0x1976F3A4);
    set(random());
    m_ziggurat.r4_nor_setup(m_ziggurat.m_kn, m_ziggurat.m_fn, m_ziggurat.m_wn);
  }

  /**
   * @brief returns a random value generated by a specific system used internally
   * @return T value the random value in T format
   */
  template<typename T>
  static T
  get() {

    float value = 0.0f;

    RANDOM_METHOD::E method = RANDOM_METHOD::E::_from_integral(m_method);

    switch (method) {
    case RANDOM_METHOD::E::eZIGGURAT:
      value = m_ziggurat.next();
      break;
    case RANDOM_METHOD::E::eMT:
      break;
    case RANDOM_METHOD::E::eBBS:
      break;
    case RANDOM_METHOD::E::eMSM:
      break;
    }

    return static_cast<T>(value);
  }

  /**
   * @brief returns a random value generated by a specific system used internally
   * @param const T& min - The minimum value (inclusive)
   * @param const T& max - The maximum value (inclusive)
   * @return T value the random value in T format
   */
  template<typename T>
  static T
  getRanged(const T& min, const T& max) {
    CY_ASSERT(max > min);
    const float range = static_cast<float>(max - min);
    constexpr static float minimum = 0e-5f;
    float value = getNormalized() * (static_cast<float>(range) - minimum);
    return min + static_cast<T>(value);
  }

  static uint32
  rollDice(const uint32 sides = 6, const uint32 count = 1) {
    CY_ASSERT(sides > 1 && count > 0);
    uint32 result = 0;
    for (uint32 i = 0; i < count; ++i) {
      result += getRanged<uint32>(1, sides);
    }
    return result;
  }

  static float
  getRangeFloat(const float& min, const float& max);

  static int32
  getRangeInt32(const int32& min, const int32& max);

  static uint32
  getRangeUint32(const uint32& min, const uint32& max);

  static void
  set(const uint32& newSeed);

  static float
  getNormalized();

  static Vector2i
  getNormVector2i();

  static Vector2f
  getNormVector2f();

  static Vector3f
  getNormVector3f();

  static Vector4f
  getNormVector4f();

  static Color
  getColor();

  static Vector2i
  getVector2i(const float& thickness);

  static Vector2f
  getVector2f(const float& thickness);

  static Vector3f
  getVector3f(const float& thickness);

  static Vector4f
  getVector4f(const float& thickness);

  static void
  changeMethod(const RANDOM_METHOD::E& method = RANDOM_METHOD::E::eZIGGURAT);

public:

  static uint32 m_seed[4];

  static Ziggurat m_ziggurat;
  static MT m_mt;

  static uint32 m_method;
};

}
